// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object CorePigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class ApiUrlOptions (
  val realtimeWsApiUrl: String,
  val internalHttpApiUrl: String,
  val restApiHttpUrl: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ApiUrlOptions {
      val realtimeWsApiUrl = pigeonVar_list[0] as String
      val internalHttpApiUrl = pigeonVar_list[1] as String
      val restApiHttpUrl = pigeonVar_list[2] as String
      return ApiUrlOptions(realtimeWsApiUrl, internalHttpApiUrl, restApiHttpUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      realtimeWsApiUrl,
      internalHttpApiUrl,
      restApiHttpUrl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ApiUrlOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return CorePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TalkSessionOptions (
  /** Your app's unique TalkJS ID. Get it from the **Settings** page of the [dashboard](https://talkjs.com/dashboard). */
  val appId: String,
  /** The `id` of the user you want to connect and act as. Any messages you send will be sent as this user. */
  val userId: String,
  /** A token to authenticate the session with. Ignored if a TalkSession object already exists for this appId + userId. */
  val token: String? = null,
  /**
   * A callback that fetches a new token from your backend and returns it. If this callback throws an error, the session will terminate. Your callback should retry failed requests. Ignored if a TalkSession object already exists for this appId + userId.
   * @suppress
   * If set to true, then `getTalkSession` will bypass the registry and create a new session
   * This option is the only way to have two sessions for the same user with different auth tokens.
   *
   * IE it's an undocumented, secret escape hatch for that specific weird niche use case.
   * It *is* designed to be used by customers, but it's undocumented so they'd only find out about it
   * if they contacted live support and we told them about it.
   */
  val forceCreateNew: Boolean? = null,
  /** @suppress */
  val signature: String? = null,
  /** @suppress */
  val apiUrls: ApiUrlOptions? = null,
  /**
   * @suppress
   *
   * note: it makes little sense to have both `host` and `apiUrls`. I intend to
   * remove `apiUrls` in the future in favour of just `host`.
   */
  val host: String? = null,
  /** @suppress */
  val clientBuild: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TalkSessionOptions {
      val appId = pigeonVar_list[0] as String
      val userId = pigeonVar_list[1] as String
      val token = pigeonVar_list[2] as String?
      val forceCreateNew = pigeonVar_list[3] as Boolean?
      val signature = pigeonVar_list[4] as String?
      val apiUrls = pigeonVar_list[5] as ApiUrlOptions?
      val host = pigeonVar_list[6] as String?
      val clientBuild = pigeonVar_list[7] as String?
      return TalkSessionOptions(appId, userId, token, forceCreateNew, signature, apiUrls, host, clientBuild)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      appId,
      userId,
      token,
      forceCreateNew,
      signature,
      apiUrls,
      host,
      clientBuild,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is TalkSessionOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return CorePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CreateUserParams (
  /** The user's name which is displayed on the TalkJS UI */
  val name: String,
  /**
   * Custom metadata you have set on the user.
   * Default = no custom metadata
   */
  val custom: Map<String, String>? = null,
  /**
   * An [IETF language tag](https://www.w3.org/International/articles/language-tags/)
   * See the [localization documentation](https://talkjs.com/docs/Features/Language_Support/Localization.html)
   * Default = the locale selected on the dashboard
   */
  val locale: String? = null,
  /**
   * An optional URL to a photo that is displayed as the user's avatar.
   * Default = no photo
   */
  val photoUrl: String? = null,
  /**
   * TalkJS supports multiple sets of settings, called "roles". These allow you to change the behavior of TalkJS for different users.
   * You have full control over which user gets which configuration.
   * Default = the `default` role
   */
  val role: String? = null,
  /**
   * The default message a person sees when starting a chat with this user.
   * Default = no welcome message
   */
  val welcomeMessage: String? = null,
  /**
   * An array of email addresses associated with the user.
   * Default = no email addresses
   */
  val email: List<String>? = null,
  /**
   * An array of phone numbers associated with the user.
   * Default = no phone numbers
   */
  val phone: List<String>? = null,
  /**
   * A Map of push registration tokens to use when notifying this user.
   *
   * Keys in the Map have the format `'provider:token_id'`, where `provider` is either
   * `"fcm"` for Firebase Cloud Messaging or `"apns"` for Apple Push Notification Service
   *
   * Default = no push registration tokens
   *
   * (Value of the Map is always true)
   */
  val pushTokens: Map<String, Boolean>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CreateUserParams {
      val name = pigeonVar_list[0] as String
      val custom = pigeonVar_list[1] as Map<String, String>?
      val locale = pigeonVar_list[2] as String?
      val photoUrl = pigeonVar_list[3] as String?
      val role = pigeonVar_list[4] as String?
      val welcomeMessage = pigeonVar_list[5] as String?
      val email = pigeonVar_list[6] as List<String>?
      val phone = pigeonVar_list[7] as List<String>?
      val pushTokens = pigeonVar_list[8] as Map<String, Boolean>?
      return CreateUserParams(name, custom, locale, photoUrl, role, welcomeMessage, email, phone, pushTokens)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      custom,
      locale,
      photoUrl,
      role,
      welcomeMessage,
      email,
      phone,
      pushTokens,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CreateUserParams) {
      return false
    }
    if (this === other) {
      return true
    }
    return CorePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SetUserParams (
  /** The user's name which will be displayed on the TalkJS UI */
  val name: String? = null,
  /**
   * Custom metadata you have set on the user.
   * This value acts as a patch. Remove specific properties by calling [UserRef.deleteFields]
   * Default = no custom metadata
   */
  val custom: Map<String, String?>? = null,
  /**
   * An [IETF language tag](https://www.w3.org/International/articles/language-tags/)
   * See the [localization documentation](https://talkjs.com/docs/Features/Language_Support/Localization.html)
   * Default = the locale selected on the dashboard
   */
  val locale: String? = null,
  /**
   * An optional URL to a photo which will be displayed as the user's avatar.
   * Default = no photo
   */
  val photoUrl: String? = null,
  /**
   * TalkJS supports multiple sets of settings, called "roles". These allow you to change the behaviour of TalkJS for
   * different users.
   * You have full control over which user gets which configuration.
   * Default = the `default` role
   */
  val role: String? = null,
  /**
   * The default message a person sees when starting a chat with this user.
   * Default = no welcome message
   */
  val welcomeMessage: String? = null,
  /**
   * An array of email addresses associated with the user.
   * Default = no email addresses
   */
  val email: List<String>? = null,
  /**
   * An array of phone numbers associated with the user.
   * Default = no phone numbers
   */
  val phone: List<String>? = null,
  /**
   * A Map of push registration tokens to use when notifying this user.
   *
   * Keys in the Map have the format `'provider:token_id'`, where `provider` is either
   * `"fcm"` for Firebase Cloud Messaging or `"apns"` for Apple Push Notification Service
   *
   * The value for each key must be `true` to register the device for push notifications.
   * To unregister that device call [UserRef.deleteFields]
   *
   * Calling [UserRef.deleteFields] with the string `pushTokens` unregisters all the previously registered devices.
   *
   * Default = no push tokens
   */
  val pushTokens: Map<String, Boolean?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SetUserParams {
      val name = pigeonVar_list[0] as String?
      val custom = pigeonVar_list[1] as Map<String, String?>?
      val locale = pigeonVar_list[2] as String?
      val photoUrl = pigeonVar_list[3] as String?
      val role = pigeonVar_list[4] as String?
      val welcomeMessage = pigeonVar_list[5] as String?
      val email = pigeonVar_list[6] as List<String>?
      val phone = pigeonVar_list[7] as List<String>?
      val pushTokens = pigeonVar_list[8] as Map<String, Boolean?>?
      return SetUserParams(name, custom, locale, photoUrl, role, welcomeMessage, email, phone, pushTokens)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      custom,
      locale,
      photoUrl,
      role,
      welcomeMessage,
      email,
      phone,
      pushTokens,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SetUserParams) {
      return false
    }
    if (this === other) {
      return true
    }
    return CorePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UserSnapshot (
  /** The unique ID that is used to identify the user in TalkJS */
  val id: String,
  /** The user's name, which is displayed on the TalkJS UI */
  val name: String,
  /** Custom metadata you have set on the user */
  val custom: Map<String, String>,
  /**
   * TalkJS supports multiple sets of settings for users, called "roles". Roles allow you to change the behavior of TalkJS for different users.
   * You have full control over which user gets which configuration.
   */
  val role: String,
  /**
   * An [IETF language tag](https://www.w3.org/International/articles/language-tags/)
   * For more information, see: [localization](https://talkjs.com/docs/Features/Language_Support/Localization.html)
   *
   * When `locale` is null, the app's default locale will be used
   */
  val locale: String? = null,
  /** An optional URL to a photo that is displayed as the user's avatar */
  val photoUrl: String? = null,
  /** The default message a person sees when starting a chat with this user */
  val welcomeMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UserSnapshot {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val custom = pigeonVar_list[2] as Map<String, String>
      val role = pigeonVar_list[3] as String
      val locale = pigeonVar_list[4] as String?
      val photoUrl = pigeonVar_list[5] as String?
      val welcomeMessage = pigeonVar_list[6] as String?
      return UserSnapshot(id, name, custom, role, locale, photoUrl, welcomeMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      custom,
      role,
      locale,
      photoUrl,
      welcomeMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is UserSnapshot) {
      return false
    }
    if (this === other) {
      return true
    }
    return CorePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UserOnlineSnapshot (
  /** The user this snapshot relates to */
  val user: UserSnapshot,
  /**
   * Whether the user is connected right now
   *
   * @remarks
   * Users are considered connected whenever they have an active websocket connection to the TalkJS servers.
   * In practice, this means:
   *
   * People using the [JS Data API](https://talkjs.com/docs/Reference/JavaScript_Data_API/) are considered connected if they are subscribed to something, or if they sent a request in the last few seconds.
   * Creating a `TalkSession` is not enough to appear connected.
   *
   * People using [Components](https://talkjs.com/docs/Reference/Components/), are considered connected if they have a UI open.
   *
   * People using the [JavaScript SDK](https://talkjs.com/docs/Reference/JavaScript_Chat_SDK/), [React SDK](https://talkjs.com/docs/Reference/React_SDK/Installation/), [React Native SDK](https://talkjs.com/docs/Reference/React_Native_SDK/Installation/), or [Flutter SDK](https://talkjs.com/docs/Reference/Flutter_SDK/Installation/) are considered connected whenever they have an active `Session` object.
   */
  val isConnected: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UserOnlineSnapshot {
      val user = pigeonVar_list[0] as UserSnapshot
      val isConnected = pigeonVar_list[1] as Boolean
      return UserOnlineSnapshot(user, isConnected)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      user,
      isConnected,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is UserOnlineSnapshot) {
      return false
    }
    if (this === other) {
      return true
    }
    return CorePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class CorePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApiUrlOptions.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TalkSessionOptions.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CreateUserParams.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SetUserParams.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UserSnapshot.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UserOnlineSnapshot.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ApiUrlOptions -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is TalkSessionOptions -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is CreateUserParams -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is SetUserParams -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is UserSnapshot -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is UserOnlineSnapshot -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CoreHostApi {
  fun getTalkSession(options: TalkSessionOptions): Long
  fun sessionDelete(handle: Long)
  fun sessionUser(handle: Long, id: String): Long
  fun userDelete(handle: Long)
  fun userGet(handle: Long, callback: (Result<UserSnapshot?>) -> Unit)
  fun userSet(handle: Long, data: SetUserParams, callback: (Result<Unit>) -> Unit)
  fun userCreateIfNotExists(handle: Long, data: CreateUserParams, callback: (Result<Unit>) -> Unit)
  fun userDeleteFields(handle: Long, fields: List<String>, callback: (Result<Unit>) -> Unit)
  fun userSubscribe(handle: Long): Long
  fun userSubscribeOnline(handle: Long): Long
  fun userSubscriptionDelete(handle: Long)
  fun userSubscriptionUnsubscribe(handle: Long)
  fun userOnlineSubscriptionDelete(handle: Long)
  fun userOnlineSubscriptionUnsubscribe(handle: Long)

  companion object {
    /** The codec used by CoreHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      CorePigeonCodec()
    }
    /** Sets up an instance of `CoreHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CoreHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.getTalkSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as TalkSessionOptions
            val wrapped: List<Any?> = try {
              listOf(api.getTalkSession(optionsArg))
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.sessionDelete$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.sessionDelete(handleArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.sessionUser$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val idArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.sessionUser(handleArg, idArg))
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userDelete$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.userDelete(handleArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userGet$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.userGet(handleArg) { result: Result<UserSnapshot?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CorePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userSet$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val dataArg = args[1] as SetUserParams
            api.userSet(handleArg, dataArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                reply.reply(CorePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userCreateIfNotExists$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val dataArg = args[1] as CreateUserParams
            api.userCreateIfNotExists(handleArg, dataArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                reply.reply(CorePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userDeleteFields$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val fieldsArg = args[1] as List<String>
            api.userDeleteFields(handleArg, fieldsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                reply.reply(CorePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userSubscribe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.userSubscribe(handleArg))
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userSubscribeOnline$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.userSubscribeOnline(handleArg))
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userSubscriptionDelete$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.userSubscriptionDelete(handleArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userSubscriptionUnsubscribe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.userSubscriptionUnsubscribe(handleArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userOnlineSubscriptionDelete$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.userOnlineSubscriptionDelete(handleArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userOnlineSubscriptionUnsubscribe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.userOnlineSubscriptionUnsubscribe(handleArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class CoreFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by CoreFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      CorePigeonCodec()
    }
  }
  fun newUserSnapshot(handleArg: Long, snapshotArg: UserSnapshot?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.talkjs_core_flutter.CoreFlutterApi.newUserSnapshot$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, snapshotArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(CorePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun newUserOnlineSnapshot(handleArg: Long, snapshotArg: UserOnlineSnapshot?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.talkjs_core_flutter.CoreFlutterApi.newUserOnlineSnapshot$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, snapshotArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(CorePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
