// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object CorePigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class ConversationAccess(val raw: Int) {
  READ(0),
  READ_WRITE(1);

  companion object {
    fun ofRaw(raw: Int): ConversationAccess? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class NotificationSettings(val raw: Int) {
  YES(0),
  NO(1),
  MENTIONS_ONLY(2);

  companion object {
    fun ofRaw(raw: Int): NotificationSettings? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class MessageType(val raw: Int) {
  USER_MESSAGE(0),
  SYSTEM_MESSAGE(1);

  companion object {
    fun ofRaw(raw: Int): MessageType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class MessageOrigin(val raw: Int) {
  WEB(0),
  REST(1),
  IMPORT(2),
  EMAIL(3);

  companion object {
    fun ofRaw(raw: Int): MessageOrigin? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ApiUrlOptions (
  val realtimeWsApiUrl: String,
  val internalHttpApiUrl: String,
  val restApiHttpUrl: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ApiUrlOptions {
      val realtimeWsApiUrl = pigeonVar_list[0] as String
      val internalHttpApiUrl = pigeonVar_list[1] as String
      val restApiHttpUrl = pigeonVar_list[2] as String
      return ApiUrlOptions(realtimeWsApiUrl, internalHttpApiUrl, restApiHttpUrl)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      realtimeWsApiUrl,
      internalHttpApiUrl,
      restApiHttpUrl,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ApiUrlOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return CorePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class TalkSessionOptions (
  /** Your app's unique TalkJS ID. Get it from the **Settings** page of the [dashboard](https://talkjs.com/dashboard). */
  val appId: String,
  /** The `id` of the user you want to connect and act as. Any messages you send will be sent as this user. */
  val userId: String,
  /** A token to authenticate the session with. Ignored if a TalkSession object already exists for this appId + userId. */
  val token: String? = null,
  /**
   * A callback that fetches a new token from your backend and returns it. If this callback throws an error, the session will terminate. Your callback should retry failed requests. Ignored if a TalkSession object already exists for this appId + userId.
   * @suppress
   * If set to true, then `getTalkSession` will bypass the registry and create a new session
   * This option is the only way to have two sessions for the same user with different auth tokens.
   *
   * IE it's an undocumented, secret escape hatch for that specific weird niche use case.
   * It *is* designed to be used by customers, but it's undocumented so they'd only find out about it
   * if they contacted live support and we told them about it.
   */
  val forceCreateNew: Boolean? = null,
  /** @suppress */
  val signature: String? = null,
  /** @suppress */
  val apiUrls: ApiUrlOptions? = null,
  /**
   * @suppress
   *
   * note: it makes little sense to have both `host` and `apiUrls`. I intend to
   * remove `apiUrls` in the future in favour of just `host`.
   */
  val host: String? = null,
  /** @suppress */
  val clientBuild: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TalkSessionOptions {
      val appId = pigeonVar_list[0] as String
      val userId = pigeonVar_list[1] as String
      val token = pigeonVar_list[2] as String?
      val forceCreateNew = pigeonVar_list[3] as Boolean?
      val signature = pigeonVar_list[4] as String?
      val apiUrls = pigeonVar_list[5] as ApiUrlOptions?
      val host = pigeonVar_list[6] as String?
      val clientBuild = pigeonVar_list[7] as String?
      return TalkSessionOptions(appId, userId, token, forceCreateNew, signature, apiUrls, host, clientBuild)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      appId,
      userId,
      token,
      forceCreateNew,
      signature,
      apiUrls,
      host,
      clientBuild,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is TalkSessionOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return CorePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CreateUserParams (
  /** The user's name which is displayed on the TalkJS UI */
  val name: String,
  /**
   * Custom metadata you have set on the user.
   * Default = no custom metadata
   */
  val custom: Map<String, String>? = null,
  /**
   * An [IETF language tag](https://www.w3.org/International/articles/language-tags/)
   * See the [localization documentation](https://talkjs.com/docs/Features/Language_Support/Localization.html)
   * Default = the locale selected on the dashboard
   */
  val locale: String? = null,
  /**
   * An optional URL to a photo that is displayed as the user's avatar.
   * Default = no photo
   */
  val photoUrl: String? = null,
  /**
   * TalkJS supports multiple sets of settings, called "roles". These allow you to change the behavior of TalkJS for different users.
   * You have full control over which user gets which configuration.
   * Default = the `default` role
   */
  val role: String? = null,
  /**
   * The default message a person sees when starting a chat with this user.
   * Default = no welcome message
   */
  val welcomeMessage: String? = null,
  /**
   * An array of email addresses associated with the user.
   * Default = no email addresses
   */
  val email: List<String>? = null,
  /**
   * An array of phone numbers associated with the user.
   * Default = no phone numbers
   */
  val phone: List<String>? = null,
  /**
   * A Map of push registration tokens to use when notifying this user.
   *
   * Keys in the Map have the format `'provider:token_id'`, where `provider` is either
   * `"fcm"` for Firebase Cloud Messaging or `"apns"` for Apple Push Notification Service
   *
   * Default = no push registration tokens
   *
   * (Value of the Map is always true)
   */
  val pushTokens: Map<String, Boolean>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CreateUserParams {
      val name = pigeonVar_list[0] as String
      val custom = pigeonVar_list[1] as Map<String, String>?
      val locale = pigeonVar_list[2] as String?
      val photoUrl = pigeonVar_list[3] as String?
      val role = pigeonVar_list[4] as String?
      val welcomeMessage = pigeonVar_list[5] as String?
      val email = pigeonVar_list[6] as List<String>?
      val phone = pigeonVar_list[7] as List<String>?
      val pushTokens = pigeonVar_list[8] as Map<String, Boolean>?
      return CreateUserParams(name, custom, locale, photoUrl, role, welcomeMessage, email, phone, pushTokens)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      custom,
      locale,
      photoUrl,
      role,
      welcomeMessage,
      email,
      phone,
      pushTokens,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CreateUserParams) {
      return false
    }
    if (this === other) {
      return true
    }
    return CorePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SetUserParams (
  /** The user's name which will be displayed on the TalkJS UI */
  val name: String? = null,
  /**
   * Custom metadata you have set on the user.
   * This value acts as a patch. Remove specific properties by calling [UserRef.deleteFields]
   * Default = no custom metadata
   */
  val custom: Map<String, String?>? = null,
  /**
   * An [IETF language tag](https://www.w3.org/International/articles/language-tags/)
   * See the [localization documentation](https://talkjs.com/docs/Features/Language_Support/Localization.html)
   * Default = the locale selected on the dashboard
   */
  val locale: String? = null,
  /**
   * An optional URL to a photo which will be displayed as the user's avatar.
   * Default = no photo
   */
  val photoUrl: String? = null,
  /**
   * TalkJS supports multiple sets of settings, called "roles". These allow you to change the behaviour of TalkJS for
   * different users.
   * You have full control over which user gets which configuration.
   * Default = the `default` role
   */
  val role: String? = null,
  /**
   * The default message a person sees when starting a chat with this user.
   * Default = no welcome message
   */
  val welcomeMessage: String? = null,
  /**
   * An array of email addresses associated with the user.
   * Default = no email addresses
   */
  val email: List<String>? = null,
  /**
   * An array of phone numbers associated with the user.
   * Default = no phone numbers
   */
  val phone: List<String>? = null,
  /**
   * A Map of push registration tokens to use when notifying this user.
   *
   * Keys in the Map have the format `'provider:token_id'`, where `provider` is either
   * `"fcm"` for Firebase Cloud Messaging or `"apns"` for Apple Push Notification Service
   *
   * The value for each key must be `true` to register the device for push notifications.
   * To unregister that device call [UserRef.deleteFields]
   *
   * Calling [UserRef.deleteFields] with the string `pushTokens` unregisters all the previously registered devices.
   *
   * Default = no push tokens
   */
  val pushTokens: Map<String, Boolean?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SetUserParams {
      val name = pigeonVar_list[0] as String?
      val custom = pigeonVar_list[1] as Map<String, String?>?
      val locale = pigeonVar_list[2] as String?
      val photoUrl = pigeonVar_list[3] as String?
      val role = pigeonVar_list[4] as String?
      val welcomeMessage = pigeonVar_list[5] as String?
      val email = pigeonVar_list[6] as List<String>?
      val phone = pigeonVar_list[7] as List<String>?
      val pushTokens = pigeonVar_list[8] as Map<String, Boolean?>?
      return SetUserParams(name, custom, locale, photoUrl, role, welcomeMessage, email, phone, pushTokens)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      custom,
      locale,
      photoUrl,
      role,
      welcomeMessage,
      email,
      phone,
      pushTokens,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SetUserParams) {
      return false
    }
    if (this === other) {
      return true
    }
    return CorePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UserSnapshot (
  /** The unique ID that is used to identify the user in TalkJS */
  val id: String,
  /** The user's name, which is displayed on the TalkJS UI */
  val name: String,
  /** Custom metadata you have set on the user */
  val custom: Map<String, String>,
  /**
   * TalkJS supports multiple sets of settings for users, called "roles". Roles allow you to change the behavior of TalkJS for different users.
   * You have full control over which user gets which configuration.
   */
  val role: String,
  /**
   * An [IETF language tag](https://www.w3.org/International/articles/language-tags/)
   * For more information, see: [localization](https://talkjs.com/docs/Features/Language_Support/Localization.html)
   *
   * When `locale` is null, the app's default locale will be used
   */
  val locale: String? = null,
  /** An optional URL to a photo that is displayed as the user's avatar */
  val photoUrl: String? = null,
  /** The default message a person sees when starting a chat with this user */
  val welcomeMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UserSnapshot {
      val id = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val custom = pigeonVar_list[2] as Map<String, String>
      val role = pigeonVar_list[3] as String
      val locale = pigeonVar_list[4] as String?
      val photoUrl = pigeonVar_list[5] as String?
      val welcomeMessage = pigeonVar_list[6] as String?
      return UserSnapshot(id, name, custom, role, locale, photoUrl, welcomeMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      name,
      custom,
      role,
      locale,
      photoUrl,
      welcomeMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is UserSnapshot) {
      return false
    }
    if (this === other) {
      return true
    }
    return CorePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UserOnlineSnapshot (
  /** The user this snapshot relates to */
  val user: UserSnapshot,
  /**
   * Whether the user is connected right now
   *
   * @remarks
   * Users are considered connected whenever they have an active websocket connection to the TalkJS servers.
   * In practice, this means:
   *
   * People using the [JS Data API](https://talkjs.com/docs/Reference/JavaScript_Data_API/) are considered connected if they are subscribed to something, or if they sent a request in the last few seconds.
   * Creating a `TalkSession` is not enough to appear connected.
   *
   * People using [Components](https://talkjs.com/docs/Reference/Components/), are considered connected if they have a UI open.
   *
   * People using the [JavaScript SDK](https://talkjs.com/docs/Reference/JavaScript_Chat_SDK/), [React SDK](https://talkjs.com/docs/Reference/React_SDK/Installation/), [React Native SDK](https://talkjs.com/docs/Reference/React_Native_SDK/Installation/), or [Flutter SDK](https://talkjs.com/docs/Reference/Flutter_SDK/Installation/) are considered connected whenever they have an active `Session` object.
   */
  val isConnected: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UserOnlineSnapshot {
      val user = pigeonVar_list[0] as UserSnapshot
      val isConnected = pigeonVar_list[1] as Boolean
      return UserOnlineSnapshot(user, isConnected)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      user,
      isConnected,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is UserOnlineSnapshot) {
      return false
    }
    if (this === other) {
      return true
    }
    return CorePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CreateConversationParams (
  /**
   * The conversation subject to display in the chat header.
   * Default = no subject, list participant names instead
   */
  val subject: String? = null,
  /**
   * The URL for the conversation photo to display in the chat header.
   * Default = no photo, show a placeholder image.
   */
  val photoUrl: String? = null,
  /**
   * System messages which are sent at the beginning of a conversation.
   * Default = no messages.
   */
  val welcomeMessages: List<String>? = null,
  /**
   * Custom metadata you have set on the conversation.
   * Default = no custom metadata
   */
  val custom: Map<String, String>? = null,
  /**
   * Your access to the conversation.
   * Default = `READ_WRITE` access.
   */
  val access: ConversationAccess? = null,
  /**
   * Your notification settings.
   * Default = `TRUE`
   */
  val notify: NotificationSettings? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CreateConversationParams {
      val subject = pigeonVar_list[0] as String?
      val photoUrl = pigeonVar_list[1] as String?
      val welcomeMessages = pigeonVar_list[2] as List<String>?
      val custom = pigeonVar_list[3] as Map<String, String>?
      val access = pigeonVar_list[4] as ConversationAccess?
      val notify = pigeonVar_list[5] as NotificationSettings?
      return CreateConversationParams(subject, photoUrl, welcomeMessages, custom, access, notify)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      subject,
      photoUrl,
      welcomeMessages,
      custom,
      access,
      notify,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CreateConversationParams) {
      return false
    }
    if (this === other) {
      return true
    }
    return CorePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SetConversationParams (
  /**
   * The conversation subject to display in the chat header.
   * Default = no subject, list participant names instead.
   */
  val subject: String? = null,
  /**
   * The URL for the conversation photo to display in the chat header.
   * Default = no photo, show a placeholder image.
   */
  val photoUrl: String? = null,
  /**
   * System messages which are sent at the beginning of a conversation.
   * Default = no messages.
   */
  val welcomeMessages: List<String>? = null,
  /**
   * Custom metadata you have set on the conversation.
   * This value acts as a patch. Remove specific properties by calling [ConversationRef.deleteFields]
   * Default = no custom metadata
   */
  val custom: Map<String, String?>? = null,
  /**
   * Your access to the conversation.
   * Default = `READ_WRITE` access.
   */
  val access: ConversationAccess? = null,
  /**
   * Your notification settings.
   * Default = `TRUE`
   */
  val notify: NotificationSettings? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SetConversationParams {
      val subject = pigeonVar_list[0] as String?
      val photoUrl = pigeonVar_list[1] as String?
      val welcomeMessages = pigeonVar_list[2] as List<String>?
      val custom = pigeonVar_list[3] as Map<String, String?>?
      val access = pigeonVar_list[4] as ConversationAccess?
      val notify = pigeonVar_list[5] as NotificationSettings?
      return SetConversationParams(subject, photoUrl, welcomeMessages, custom, access, notify)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      subject,
      photoUrl,
      welcomeMessages,
      custom,
      access,
      notify,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SetConversationParams) {
      return false
    }
    if (this === other) {
      return true
    }
    return CorePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ReactionSnapshot (
  /** Which emoji the users reacted with. */
  val emoji: String,
  /** The number of times this emoji has been added to the message. */
  val count: Long,
  /** Whether the current user has reacted to the message with this emoji. */
  val currentUserReacted: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ReactionSnapshot {
      val emoji = pigeonVar_list[0] as String
      val count = pigeonVar_list[1] as Long
      val currentUserReacted = pigeonVar_list[2] as Boolean
      return ReactionSnapshot(emoji, count, currentUserReacted)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      emoji,
      count,
      currentUserReacted,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ReactionSnapshot) {
      return false
    }
    if (this === other) {
      return true
    }
    return CorePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ReferencedMessageSnapshot (
  /** The unique ID that is used to identify the message in TalkJS */
  val id: String,
  /** Referenced messages are always `USER_MESSAGE` because you cannot reply to a system message. */
  val type: MessageType,
  /**
   * A snapshot of the user who sent the message.
   * The user's attributes may have been updated since they sent the message, in which case this snapshot contains the updated data.
   * It is not a historical snapshot.
   *
   * @remarks
   * Guaranteed to be set, unlike in MessageSnapshot, because you cannot reference a SystemMessage
   */
  val sender: UserSnapshot? = null,
  /** Custom metadata you have set on the message */
  val custom: Map<String, String>,
  /** Time at which the message was sent, as a unix timestamp in milliseconds */
  val createdAt: Long,
  /**
   * Time at which the message was last edited, as a unix timestamp in milliseconds.
   * `null` if the message has never been edited.
   */
  val editedAt: Long? = null,
  /**
   * The ID of the message that this message is a reply to, or null if this message is not a reply.
   *
   * @remarks
   * Since this is a snapshot of a referenced message, we do not automatically expand its referenced message.
   * The ID of its referenced message is provided here instead.
   */
  val referencedMessageId: String? = null,
  /**
   * Where this message originated from:
   *
   * - `WEB` = Message sent via the UI or via `ConversationBuilder.sendMessage`
   *
   * - `REST` = Message sent via the REST API's "send message" endpoint
   *
   * - `IMPORT` = Message sent via the REST API's "import messages" endpoint
   *
   * - `EMAIL` = Message sent by replying to an email notification
   */
  val origin: MessageOrigin,
  /**
   * The contents of the message, as a plain text string without any formatting or attachments.
   * Useful for showing in a conversation list or in notifications.
   */
  val plaintext: String,
  /**
   * The main body of the message, as a list of blocks that are rendered top-to-bottom.
   * All the emoji reactions that have been added to this message.
   */
  val reactions: List<ReactionSnapshot>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ReferencedMessageSnapshot {
      val id = pigeonVar_list[0] as String
      val type = pigeonVar_list[1] as MessageType
      val sender = pigeonVar_list[2] as UserSnapshot?
      val custom = pigeonVar_list[3] as Map<String, String>
      val createdAt = pigeonVar_list[4] as Long
      val editedAt = pigeonVar_list[5] as Long?
      val referencedMessageId = pigeonVar_list[6] as String?
      val origin = pigeonVar_list[7] as MessageOrigin
      val plaintext = pigeonVar_list[8] as String
      val reactions = pigeonVar_list[9] as List<ReactionSnapshot>
      return ReferencedMessageSnapshot(id, type, sender, custom, createdAt, editedAt, referencedMessageId, origin, plaintext, reactions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      type,
      sender,
      custom,
      createdAt,
      editedAt,
      referencedMessageId,
      origin,
      plaintext,
      reactions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ReferencedMessageSnapshot) {
      return false
    }
    if (this === other) {
      return true
    }
    return CorePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MessageSnapshot (
  /** The unique ID that is used to identify the message in TalkJS */
  val id: String,
  /**
   * Whether this message was "from a user" or a general system message without a specific sender.
   *
   * The `sender` property is always present for `USER_MESSAGE` messages and never present for `SYSTEM_MESSAGE` messages.
   */
  val type: MessageType,
  /**
   * A snapshot of the user who sent the message, or null if it is a system message.
   * The user's attributes may have been updated since they sent the message, in which case this snapshot contains the updated data.
   * It is not a historical snapshot.
   */
  val sender: UserSnapshot? = null,
  /** Custom metadata you have set on the message */
  val custom: Map<String, String>,
  /** Time at which the message was sent, as a unix timestamp in milliseconds. */
  val createdAt: Long,
  /**
   * Time at which the message was last edited, as a unix timestamp in milliseconds.
   * `null` if the message has never been edited.
   */
  val editedAt: Long? = null,
  /**
   * A snapshot of the message that this message is aa reply to, or `null` if this message is not a reply.
   *
   * Only UserMessages can reference other messages.
   * The referenced message snapshot does not have a `referencedMessage` field.
   * Instead, it has `referencedMessageId`.
   * This prevents TalkJS fetching an unlimited number of messages in a long chain of replies.
   */
  val referencedMessage: ReferencedMessageSnapshot? = null,
  /**
   * Where this message origiranted from:
   *
   * - `WEB` = Message sent via the UI or via `ConversationBuilder.sendMessage`
   * - `REST` = Message sent via the REST API's "send message" endpoint
   * - `IMPORT` = Message sent via the REST API's "import messages" endpoint
   * - `EMAIL` = Message sent by replying to an email notification
   */
  val origin: MessageOrigin,
  /**
   * The contents of the message, as a plain text string without any formatting or attachments.
   * Useful for showing in a conversation list or in notifications.
   */
  val plaintext: String,
  /**
   * The main body of the message, as a list of blocks that are rendered top-to-bottom.
   * All the emoji reactions that have been added to this message.
   *
   * @remarks
   * There can be up to 50 different reactions on each message.
   */
  val reactions: List<ReactionSnapshot>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MessageSnapshot {
      val id = pigeonVar_list[0] as String
      val type = pigeonVar_list[1] as MessageType
      val sender = pigeonVar_list[2] as UserSnapshot?
      val custom = pigeonVar_list[3] as Map<String, String>
      val createdAt = pigeonVar_list[4] as Long
      val editedAt = pigeonVar_list[5] as Long?
      val referencedMessage = pigeonVar_list[6] as ReferencedMessageSnapshot?
      val origin = pigeonVar_list[7] as MessageOrigin
      val plaintext = pigeonVar_list[8] as String
      val reactions = pigeonVar_list[9] as List<ReactionSnapshot>
      return MessageSnapshot(id, type, sender, custom, createdAt, editedAt, referencedMessage, origin, plaintext, reactions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      type,
      sender,
      custom,
      createdAt,
      editedAt,
      referencedMessage,
      origin,
      plaintext,
      reactions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MessageSnapshot) {
      return false
    }
    if (this === other) {
      return true
    }
    return CorePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConversationSnapshot (
  /** The ID of the conversation */
  val id: String,
  /** Contains the conversation subject, or `null` if the conversation does not have a subject specified. */
  val subject: String? = null,
  /** Contains the URL of a photo to represent the topic of the conversation or `null` if the conversation does not have a photo specified. */
  val photoUrl: String? = null,
  /**
   * One or more welcome messages that will be rendered at the start of this conversation as system messages.
   *
   * @remarks
   * Welcome messages are rendered in the UI as messages, but they are not real messages.
   * This means they do not appear when you list messages using the REST API or JS/Kotlin Data API, and you cannot reply or react to them.
   */
  val welcomeMessages: List<String>,
  /** Custom metadata you have set on the conversation */
  val custom: Map<String, String>,
  /** The date that the conversation was created, as a unix timestamp in milliseconds. */
  val createdAt: Long,
  /** The date that the current user joined the conversation, as a unix timestamp in milliseconds. */
  val joinedAt: Long,
  /** The last message sent in this conversation, or `null` if not messages have been sent. */
  val lastMessage: MessageSnapshot? = null,
  /** The number of messages in this conversation that the current user hasn't read. */
  val unreadMessageCount: Long,
  /**
   * The most recent date that the current user read the conversation.
   *
   * @remarks
   * This value is updated whenever you read a message in a chat UI, open an email notification, or mark the conversation as read using an API like [ConversationRef.markAsRead].
   *
   * Any messages sent after this timestamp are unread messages.
   */
  val readUntil: Long,
  /**
   * Everyone in the conversation has read any messages sent on or before this date.
   *
   * @remarks
   * This is the minimum of all the participants' `readUntil` values.
   * Any messages sent on or before this timestamp should show a "read" indicator in the UI.
   *
   * This value will rarely change in very large conversations.
   * If just one person stops checking their messages, `everyoneReadUntil` will never update.
   */
  val everyoneReadUntil: Long,
  /**
   * Whether the conversation should be considered unread.
   *
   * This can be true even when `unreadMessageCount` is zero, if the user has manually marked the conversation as unread.
   */
  val isUnread: Boolean,
  /** The current user's permission level in this conversation. */
  val access: ConversationAccess,
  /**
   * The current user's notification settings for this conversation.
   *
   * `FALSE` means no notifications, `TRUE` means notifications for all messages, and `MENTIONS_ONLY` means that the user will only be notified when they are mentioned with an `@`.
   */
  val notify: NotificationSettings,
  /**
   * @suppress
   * For back-compat
   */
  val lastMessageAt: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConversationSnapshot {
      val id = pigeonVar_list[0] as String
      val subject = pigeonVar_list[1] as String?
      val photoUrl = pigeonVar_list[2] as String?
      val welcomeMessages = pigeonVar_list[3] as List<String>
      val custom = pigeonVar_list[4] as Map<String, String>
      val createdAt = pigeonVar_list[5] as Long
      val joinedAt = pigeonVar_list[6] as Long
      val lastMessage = pigeonVar_list[7] as MessageSnapshot?
      val unreadMessageCount = pigeonVar_list[8] as Long
      val readUntil = pigeonVar_list[9] as Long
      val everyoneReadUntil = pigeonVar_list[10] as Long
      val isUnread = pigeonVar_list[11] as Boolean
      val access = pigeonVar_list[12] as ConversationAccess
      val notify = pigeonVar_list[13] as NotificationSettings
      val lastMessageAt = pigeonVar_list[14] as Long?
      return ConversationSnapshot(id, subject, photoUrl, welcomeMessages, custom, createdAt, joinedAt, lastMessage, unreadMessageCount, readUntil, everyoneReadUntil, isUnread, access, notify, lastMessageAt)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      subject,
      photoUrl,
      welcomeMessages,
      custom,
      createdAt,
      joinedAt,
      lastMessage,
      unreadMessageCount,
      readUntil,
      everyoneReadUntil,
      isUnread,
      access,
      notify,
      lastMessageAt,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ConversationSnapshot) {
      return false
    }
    if (this === other) {
      return true
    }
    return CorePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SetParticipantParams (
  /**
   * The level of access the participant should have in the conversation.
   * Default = `READ_WRITE` access.
   */
  val access: ConversationAccess? = null,
  /**
   * When the participant should be notified about new messages in this conversation.
   * Default = `TRUE`.
   *
   * `FALSE` means no notifications, `TRUE` means notifications for all messages, and `MENTIONS_ONLY` means that the user will only be notified when they are mentioned with an `@`.
   */
  val notify: NotificationSettings? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SetParticipantParams {
      val access = pigeonVar_list[0] as ConversationAccess?
      val notify = pigeonVar_list[1] as NotificationSettings?
      return SetParticipantParams(access, notify)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      access,
      notify,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SetParticipantParams) {
      return false
    }
    if (this === other) {
      return true
    }
    return CorePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CreateParticipantParams (
  /**
   * The level of access the participant should have in the conversation.
   * Default = `READ_WRITE` access.
   */
  val access: ConversationAccess? = null,
  /**
   * When the participant should be notified about new messages in this conversation.
   * Default = `TRUE`.
   *
   * `FALSE` means no notifications, `TRUE` means notifications for all messages, and `MENTIONS_ONLY` means that the user will only be notified when they are mentioned with an `@`.
   */
  val notify: NotificationSettings? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CreateParticipantParams {
      val access = pigeonVar_list[0] as ConversationAccess?
      val notify = pigeonVar_list[1] as NotificationSettings?
      return CreateParticipantParams(access, notify)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      access,
      notify,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CreateParticipantParams) {
      return false
    }
    if (this === other) {
      return true
    }
    return CorePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ParticipantSnapshot (
  /** The user who this Participant Snapshot is referring to */
  val user: UserSnapshot,
  /** The level of access this participant has in the conversation. */
  val access: ConversationAccess,
  /**
   * When the participant will be notified about new messages in this conversation.
   *
   * `FALSE` means no notifications, `TRUE` means notifications for all messages, and `MENTIONS_ONLY` means that the user will only be notified when they are mentioned with an `@`.
   */
  val notify: NotificationSettings,
  /** The date that this user joined the conversation, as a unix timestamp in milliseconds. */
  val joinedAt: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ParticipantSnapshot {
      val user = pigeonVar_list[0] as UserSnapshot
      val access = pigeonVar_list[1] as ConversationAccess
      val notify = pigeonVar_list[2] as NotificationSettings
      val joinedAt = pigeonVar_list[3] as Long
      return ParticipantSnapshot(user, access, notify, joinedAt)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      user,
      access,
      notify,
      joinedAt,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ParticipantSnapshot) {
      return false
    }
    if (this === other) {
      return true
    }
    return CorePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class CorePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ConversationAccess.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NotificationSettings.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MessageType.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MessageOrigin.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ApiUrlOptions.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TalkSessionOptions.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CreateUserParams.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SetUserParams.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UserSnapshot.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UserOnlineSnapshot.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CreateConversationParams.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SetConversationParams.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ReactionSnapshot.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ReferencedMessageSnapshot.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MessageSnapshot.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConversationSnapshot.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SetParticipantParams.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CreateParticipantParams.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ParticipantSnapshot.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ConversationAccess -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is NotificationSettings -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is MessageType -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is MessageOrigin -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is ApiUrlOptions -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is TalkSessionOptions -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is CreateUserParams -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is SetUserParams -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is UserSnapshot -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is UserOnlineSnapshot -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is CreateConversationParams -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is SetConversationParams -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is ReactionSnapshot -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is ReferencedMessageSnapshot -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is MessageSnapshot -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is ConversationSnapshot -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is SetParticipantParams -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is CreateParticipantParams -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is ParticipantSnapshot -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface CoreHostApi {
  fun getTalkSession(options: TalkSessionOptions): Long
  fun sessionDeleteHandle(handle: Long)
  fun sessionUser(handle: Long, id: String): Long
  fun sessionConversation(handle: Long, id: String): Long
  fun userDeleteHandle(handle: Long)
  fun userGet(handle: Long, callback: (Result<UserSnapshot?>) -> Unit)
  fun userSet(handle: Long, data: SetUserParams, callback: (Result<Unit>) -> Unit)
  fun userCreateIfNotExists(handle: Long, data: CreateUserParams, callback: (Result<Unit>) -> Unit)
  fun userDeleteFields(handle: Long, fields: List<String>, callback: (Result<Unit>) -> Unit)
  fun userSubscribe(handle: Long): Long
  fun userSubscribeOnline(handle: Long): Long
  fun userSubscriptionDeleteHandle(handle: Long)
  fun userSubscriptionUnsubscribe(handle: Long)
  fun userOnlineSubscriptionDeleteHandle(handle: Long)
  fun userOnlineSubscriptionUnsubscribe(handle: Long)
  fun conversationDeleteHandle(handle: Long)
  fun conversationGet(handle: Long, callback: (Result<ConversationSnapshot?>) -> Unit)
  fun conversationSet(handle: Long, data: SetConversationParams, callback: (Result<Unit>) -> Unit)
  fun conversationCreateIfNotExists(handle: Long, data: CreateConversationParams, callback: (Result<Unit>) -> Unit)
  fun conversationDeleteFields(handle: Long, fields: List<String>, callback: (Result<Unit>) -> Unit)
  fun conversationParticipant(handle: Long, user: String): Long
  fun conversationMessage(handle: Long, messageId: String): Long
  fun conversationSubscribe(handle: Long): Long
  fun conversationSubscriptionDeleteHandle(handle: Long)
  fun conversationSubscriptionUnsubscribe(handle: Long)
  fun participantDeleteHandle(handle: Long)
  fun participantGet(handle: Long, callback: (Result<ParticipantSnapshot?>) -> Unit)
  fun participantSet(handle: Long, data: SetParticipantParams, callback: (Result<Unit>) -> Unit)
  fun participantEdit(handle: Long, data: SetParticipantParams, callback: (Result<Unit>) -> Unit)
  fun participantCreateIfNotExists(handle: Long, data: CreateParticipantParams, callback: (Result<Unit>) -> Unit)
  fun participantDeleteFields(handle: Long, fields: List<String>, callback: (Result<Unit>) -> Unit)
  fun participantDelete(handle: Long, callback: (Result<Unit>) -> Unit)
  fun messageDeleteHandle(handle: Long)
  fun messageGet(handle: Long, callback: (Result<MessageSnapshot?>) -> Unit)
  fun messageEdit(handle: Long, params: String, callback: (Result<Unit>) -> Unit)
  fun messageDeleteFields(handle: Long, fields: List<String>, callback: (Result<Unit>) -> Unit)
  fun messageDelete(handle: Long, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by CoreHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      CorePigeonCodec()
    }
    /** Sets up an instance of `CoreHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: CoreHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.getTalkSession$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as TalkSessionOptions
            val wrapped: List<Any?> = try {
              listOf(api.getTalkSession(optionsArg))
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.sessionDeleteHandle$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.sessionDeleteHandle(handleArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.sessionUser$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val idArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.sessionUser(handleArg, idArg))
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.sessionConversation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val idArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.sessionConversation(handleArg, idArg))
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userDeleteHandle$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.userDeleteHandle(handleArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userGet$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.userGet(handleArg) { result: Result<UserSnapshot?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CorePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userSet$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val dataArg = args[1] as SetUserParams
            api.userSet(handleArg, dataArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                reply.reply(CorePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userCreateIfNotExists$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val dataArg = args[1] as CreateUserParams
            api.userCreateIfNotExists(handleArg, dataArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                reply.reply(CorePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userDeleteFields$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val fieldsArg = args[1] as List<String>
            api.userDeleteFields(handleArg, fieldsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                reply.reply(CorePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userSubscribe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.userSubscribe(handleArg))
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userSubscribeOnline$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.userSubscribeOnline(handleArg))
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userSubscriptionDeleteHandle$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.userSubscriptionDeleteHandle(handleArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userSubscriptionUnsubscribe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.userSubscriptionUnsubscribe(handleArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userOnlineSubscriptionDeleteHandle$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.userOnlineSubscriptionDeleteHandle(handleArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userOnlineSubscriptionUnsubscribe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.userOnlineSubscriptionUnsubscribe(handleArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.conversationDeleteHandle$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.conversationDeleteHandle(handleArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.conversationGet$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.conversationGet(handleArg) { result: Result<ConversationSnapshot?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CorePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.conversationSet$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val dataArg = args[1] as SetConversationParams
            api.conversationSet(handleArg, dataArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                reply.reply(CorePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.conversationCreateIfNotExists$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val dataArg = args[1] as CreateConversationParams
            api.conversationCreateIfNotExists(handleArg, dataArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                reply.reply(CorePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.conversationDeleteFields$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val fieldsArg = args[1] as List<String>
            api.conversationDeleteFields(handleArg, fieldsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                reply.reply(CorePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.conversationParticipant$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val userArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.conversationParticipant(handleArg, userArg))
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.conversationMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val messageIdArg = args[1] as String
            val wrapped: List<Any?> = try {
              listOf(api.conversationMessage(handleArg, messageIdArg))
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.conversationSubscribe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              listOf(api.conversationSubscribe(handleArg))
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.conversationSubscriptionDeleteHandle$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.conversationSubscriptionDeleteHandle(handleArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.conversationSubscriptionUnsubscribe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.conversationSubscriptionUnsubscribe(handleArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.participantDeleteHandle$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.participantDeleteHandle(handleArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.participantGet$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.participantGet(handleArg) { result: Result<ParticipantSnapshot?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CorePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.participantSet$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val dataArg = args[1] as SetParticipantParams
            api.participantSet(handleArg, dataArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                reply.reply(CorePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.participantEdit$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val dataArg = args[1] as SetParticipantParams
            api.participantEdit(handleArg, dataArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                reply.reply(CorePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.participantCreateIfNotExists$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val dataArg = args[1] as CreateParticipantParams
            api.participantCreateIfNotExists(handleArg, dataArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                reply.reply(CorePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.participantDeleteFields$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val fieldsArg = args[1] as List<String>
            api.participantDeleteFields(handleArg, fieldsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                reply.reply(CorePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.participantDelete$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.participantDelete(handleArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                reply.reply(CorePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.messageDeleteHandle$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.messageDeleteHandle(handleArg)
              listOf(null)
            } catch (exception: Throwable) {
              CorePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.messageGet$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.messageGet(handleArg) { result: Result<MessageSnapshot?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(CorePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.messageEdit$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val paramsArg = args[1] as String
            api.messageEdit(handleArg, paramsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                reply.reply(CorePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.messageDeleteFields$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val fieldsArg = args[1] as List<String>
            api.messageDeleteFields(handleArg, fieldsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                reply.reply(CorePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.messageDelete$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            api.messageDelete(handleArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(CorePigeonUtils.wrapError(error))
              } else {
                reply.reply(CorePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class CoreFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by CoreFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      CorePigeonCodec()
    }
  }
  fun newUserSnapshot(handleArg: Long, snapshotArg: UserSnapshot?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.talkjs_core_flutter.CoreFlutterApi.newUserSnapshot$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, snapshotArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(CorePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun newUserOnlineSnapshot(handleArg: Long, snapshotArg: UserOnlineSnapshot?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.talkjs_core_flutter.CoreFlutterApi.newUserOnlineSnapshot$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, snapshotArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(CorePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun newConversationSnapshot(handleArg: Long, snapshotArg: ConversationSnapshot?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.talkjs_core_flutter.CoreFlutterApi.newConversationSnapshot$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, snapshotArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(CorePigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
