// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every(
          (MapEntry<Object?, Object?> entry) =>
              (b as Map<Object?, Object?>).containsKey(entry.key) &&
              _deepEquals(entry.value, b[entry.key]),
        );
  }
  return a == b;
}

class ApiUrlOptions {
  ApiUrlOptions({
    required this.realtimeWsApiUrl,
    required this.internalHttpApiUrl,
    required this.restApiHttpUrl,
  });

  String realtimeWsApiUrl;

  String internalHttpApiUrl;

  String restApiHttpUrl;

  List<Object?> _toList() {
    return <Object?>[realtimeWsApiUrl, internalHttpApiUrl, restApiHttpUrl];
  }

  Object encode() {
    return _toList();
  }

  static ApiUrlOptions decode(Object result) {
    result as List<Object?>;
    return ApiUrlOptions(
      realtimeWsApiUrl: result[0]! as String,
      internalHttpApiUrl: result[1]! as String,
      restApiHttpUrl: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ApiUrlOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class TalkSessionOptions {
  TalkSessionOptions({
    required this.appId,
    required this.userId,
    this.token,
    this.forceCreateNew,
    this.signature,
    this.apiUrls,
    this.host,
    this.clientBuild,
  });

  /// Your app's unique TalkJS ID. Get it from the **Settings** page of the [dashboard](https://talkjs.com/dashboard).
  String appId;

  /// The `id` of the user you want to connect and act as. Any messages you send will be sent as this user.
  String userId;

  /// A token to authenticate the session with. Ignored if a TalkSession object already exists for this appId + userId.
  String? token;

  /// A callback that fetches a new token from your backend and returns it. If this callback throws an error, the session will terminate. Your callback should retry failed requests. Ignored if a TalkSession object already exists for this appId + userId.
  /// @suppress
  /// If set to true, then `getTalkSession` will bypass the registry and create a new session
  /// This option is the only way to have two sessions for the same user with different auth tokens.
  ///
  /// IE it's an undocumented, secret escape hatch for that specific weird niche use case.
  /// It *is* designed to be used by customers, but it's undocumented so they'd only find out about it
  /// if they contacted live support and we told them about it.
  bool? forceCreateNew;

  /// @suppress
  String? signature;

  /// @suppress
  ApiUrlOptions? apiUrls;

  /// @suppress
  ///
  /// note: it makes little sense to have both `host` and `apiUrls`. I intend to
  /// remove `apiUrls` in the future in favour of just `host`.
  String? host;

  /// @suppress
  String? clientBuild;

  List<Object?> _toList() {
    return <Object?>[
      appId,
      userId,
      token,
      forceCreateNew,
      signature,
      apiUrls,
      host,
      clientBuild,
    ];
  }

  Object encode() {
    return _toList();
  }

  static TalkSessionOptions decode(Object result) {
    result as List<Object?>;
    return TalkSessionOptions(
      appId: result[0]! as String,
      userId: result[1]! as String,
      token: result[2] as String?,
      forceCreateNew: result[3] as bool?,
      signature: result[4] as String?,
      apiUrls: result[5] as ApiUrlOptions?,
      host: result[6] as String?,
      clientBuild: result[7] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TalkSessionOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class CreateUserParams {
  CreateUserParams({
    required this.name,
    this.custom,
    this.locale,
    this.photoUrl,
    this.role,
    this.welcomeMessage,
    this.email,
    this.phone,
    this.pushTokens,
  });

  /// The user's name which is displayed on the TalkJS UI
  String name;

  /// Custom metadata you have set on the user.
  /// Default = no custom metadata
  Map<String, String>? custom;

  /// An [IETF language tag](https://www.w3.org/International/articles/language-tags/)
  /// See the [localization documentation](https://talkjs.com/docs/Features/Language_Support/Localization.html)
  /// Default = the locale selected on the dashboard
  String? locale;

  /// An optional URL to a photo that is displayed as the user's avatar.
  /// Default = no photo
  String? photoUrl;

  /// TalkJS supports multiple sets of settings, called "roles". These allow you to change the behavior of TalkJS for different users.
  /// You have full control over which user gets which configuration.
  /// Default = the `default` role
  String? role;

  /// The default message a person sees when starting a chat with this user.
  /// Default = no welcome message
  String? welcomeMessage;

  /// An array of email addresses associated with the user.
  /// Default = no email addresses
  List<String>? email;

  /// An array of phone numbers associated with the user.
  /// Default = no phone numbers
  List<String>? phone;

  /// A Map of push registration tokens to use when notifying this user.
  ///
  /// Keys in the Map have the format `'provider:token_id'`, where `provider` is either
  /// `"fcm"` for Firebase Cloud Messaging or `"apns"` for Apple Push Notification Service
  ///
  /// Default = no push registration tokens
  ///
  /// (Value of the Map is always true)
  Map<String, bool>? pushTokens;

  List<Object?> _toList() {
    return <Object?>[
      name,
      custom,
      locale,
      photoUrl,
      role,
      welcomeMessage,
      email,
      phone,
      pushTokens,
    ];
  }

  Object encode() {
    return _toList();
  }

  static CreateUserParams decode(Object result) {
    result as List<Object?>;
    return CreateUserParams(
      name: result[0]! as String,
      custom: (result[1] as Map<Object?, Object?>?)?.cast<String, String>(),
      locale: result[2] as String?,
      photoUrl: result[3] as String?,
      role: result[4] as String?,
      welcomeMessage: result[5] as String?,
      email: (result[6] as List<Object?>?)?.cast<String>(),
      phone: (result[7] as List<Object?>?)?.cast<String>(),
      pushTokens: (result[8] as Map<Object?, Object?>?)?.cast<String, bool>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CreateUserParams || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class SetUserParams {
  SetUserParams({
    this.name,
    this.custom,
    this.locale,
    this.photoUrl,
    this.role,
    this.welcomeMessage,
    this.email,
    this.phone,
    this.pushTokens,
  });

  /// The user's name which will be displayed on the TalkJS UI
  String? name;

  /// Custom metadata you have set on the user.
  /// This value acts as a patch. Remove specific properties by calling [UserRef.deleteFields]
  /// Default = no custom metadata
  Map<String, String?>? custom;

  /// An [IETF language tag](https://www.w3.org/International/articles/language-tags/)
  /// See the [localization documentation](https://talkjs.com/docs/Features/Language_Support/Localization.html)
  /// Default = the locale selected on the dashboard
  String? locale;

  /// An optional URL to a photo which will be displayed as the user's avatar.
  /// Default = no photo
  String? photoUrl;

  /// TalkJS supports multiple sets of settings, called "roles". These allow you to change the behaviour of TalkJS for
  /// different users.
  /// You have full control over which user gets which configuration.
  /// Default = the `default` role
  String? role;

  /// The default message a person sees when starting a chat with this user.
  /// Default = no welcome message
  String? welcomeMessage;

  /// An array of email addresses associated with the user.
  /// Default = no email addresses
  List<String>? email;

  /// An array of phone numbers associated with the user.
  /// Default = no phone numbers
  List<String>? phone;

  /// A Map of push registration tokens to use when notifying this user.
  ///
  /// Keys in the Map have the format `'provider:token_id'`, where `provider` is either
  /// `"fcm"` for Firebase Cloud Messaging or `"apns"` for Apple Push Notification Service
  ///
  /// The value for each key must be `true` to register the device for push notifications.
  /// To unregister that device call [UserRef.deleteFields]
  ///
  /// Calling [UserRef.deleteFields] with the string `pushTokens` unregisters all the previously registered devices.
  ///
  /// Default = no push tokens
  Map<String, bool?>? pushTokens;

  List<Object?> _toList() {
    return <Object?>[
      name,
      custom,
      locale,
      photoUrl,
      role,
      welcomeMessage,
      email,
      phone,
      pushTokens,
    ];
  }

  Object encode() {
    return _toList();
  }

  static SetUserParams decode(Object result) {
    result as List<Object?>;
    return SetUserParams(
      name: result[0] as String?,
      custom: (result[1] as Map<Object?, Object?>?)?.cast<String, String?>(),
      locale: result[2] as String?,
      photoUrl: result[3] as String?,
      role: result[4] as String?,
      welcomeMessage: result[5] as String?,
      email: (result[6] as List<Object?>?)?.cast<String>(),
      phone: (result[7] as List<Object?>?)?.cast<String>(),
      pushTokens: (result[8] as Map<Object?, Object?>?)?.cast<String, bool?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SetUserParams || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class UserSnapshot {
  UserSnapshot({
    required this.id,
    required this.name,
    required this.custom,
    required this.role,
    this.locale,
    this.photoUrl,
    this.welcomeMessage,
  });

  /// The unique ID that is used to identify the user in TalkJS
  String id;

  /// The user's name, which is displayed on the TalkJS UI
  String name;

  /// Custom metadata you have set on the user
  Map<String, String> custom;

  /// TalkJS supports multiple sets of settings for users, called "roles". Roles allow you to change the behavior of TalkJS for different users.
  /// You have full control over which user gets which configuration.
  String role;

  /// An [IETF language tag](https://www.w3.org/International/articles/language-tags/)
  /// For more information, see: [localization](https://talkjs.com/docs/Features/Language_Support/Localization.html)
  ///
  /// When `locale` is null, the app's default locale will be used
  String? locale;

  /// An optional URL to a photo that is displayed as the user's avatar
  String? photoUrl;

  /// The default message a person sees when starting a chat with this user
  String? welcomeMessage;

  List<Object?> _toList() {
    return <Object?>[id, name, custom, role, locale, photoUrl, welcomeMessage];
  }

  Object encode() {
    return _toList();
  }

  static UserSnapshot decode(Object result) {
    result as List<Object?>;
    return UserSnapshot(
      id: result[0]! as String,
      name: result[1]! as String,
      custom: (result[2] as Map<Object?, Object?>?)!.cast<String, String>(),
      role: result[3]! as String,
      locale: result[4] as String?,
      photoUrl: result[5] as String?,
      welcomeMessage: result[6] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UserSnapshot || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class UserOnlineSnapshot {
  UserOnlineSnapshot({required this.user, required this.isConnected});

  /// The user this snapshot relates to
  UserSnapshot user;

  /// Whether the user is connected right now
  ///
  /// @remarks
  /// Users are considered connected whenever they have an active websocket connection to the TalkJS servers.
  /// In practice, this means:
  ///
  /// People using the [JS Data API](https://talkjs.com/docs/Reference/JavaScript_Data_API/) are considered connected if they are subscribed to something, or if they sent a request in the last few seconds.
  /// Creating a `TalkSession` is not enough to appear connected.
  ///
  /// People using [Components](https://talkjs.com/docs/Reference/Components/), are considered connected if they have a UI open.
  ///
  /// People using the [JavaScript SDK](https://talkjs.com/docs/Reference/JavaScript_Chat_SDK/), [React SDK](https://talkjs.com/docs/Reference/React_SDK/Installation/), [React Native SDK](https://talkjs.com/docs/Reference/React_Native_SDK/Installation/), or [Flutter SDK](https://talkjs.com/docs/Reference/Flutter_SDK/Installation/) are considered connected whenever they have an active `Session` object.
  bool isConnected;

  List<Object?> _toList() {
    return <Object?>[user, isConnected];
  }

  Object encode() {
    return _toList();
  }

  static UserOnlineSnapshot decode(Object result) {
    result as List<Object?>;
    return UserOnlineSnapshot(
      user: result[0]! as UserSnapshot,
      isConnected: result[1]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UserOnlineSnapshot || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is ApiUrlOptions) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is TalkSessionOptions) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is CreateUserParams) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is SetUserParams) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is UserSnapshot) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is UserOnlineSnapshot) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return ApiUrlOptions.decode(readValue(buffer)!);
      case 130:
        return TalkSessionOptions.decode(readValue(buffer)!);
      case 131:
        return CreateUserParams.decode(readValue(buffer)!);
      case 132:
        return SetUserParams.decode(readValue(buffer)!);
      case 133:
        return UserSnapshot.decode(readValue(buffer)!);
      case 134:
        return UserOnlineSnapshot.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class CoreHostApi {
  /// Constructor for [CoreHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  CoreHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<int> getTalkSession(TalkSessionOptions options) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.getTalkSession$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[options],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }

  Future<void> sessionDelete(int handle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.sessionDelete$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<int> sessionUser(int handle, String id) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.sessionUser$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle, id],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }

  Future<void> userDelete(int handle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userDelete$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<UserSnapshot?> userGet(int handle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userGet$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as UserSnapshot?);
    }
  }

  Future<void> userSet(int handle, SetUserParams data) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userSet$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle, data],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> userCreateIfNotExists(int handle, CreateUserParams data) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userCreateIfNotExists$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle, data],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> userDeleteFields(int handle, List<String> fields) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userDeleteFields$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle, fields],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<int> userSubscribe(int handle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userSubscribe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }

  Future<int> userSubscribeOnline(int handle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userSubscribeOnline$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }

  Future<void> userSubscriptionDelete(int handle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userSubscriptionDelete$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> userSubscriptionUnsubscribe(int handle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userSubscriptionUnsubscribe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> userOnlineSubscriptionDelete(int handle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userOnlineSubscriptionDelete$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> userOnlineSubscriptionUnsubscribe(int handle) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.talkjs_core_flutter.CoreHostApi.userOnlineSubscriptionUnsubscribe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[handle],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class CoreFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void newUserSnapshot(int handle, UserSnapshot? snapshot);

  void newUserOnlineSnapshot(int handle, UserOnlineSnapshot? snapshot);

  static void setUp(
    CoreFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.talkjs_core_flutter.CoreFlutterApi.newUserSnapshot$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.talkjs_core_flutter.CoreFlutterApi.newUserSnapshot was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_handle = (args[0] as int?);
          assert(
            arg_handle != null,
            'Argument for dev.flutter.pigeon.talkjs_core_flutter.CoreFlutterApi.newUserSnapshot was null, expected non-null int.',
          );
          final UserSnapshot? arg_snapshot = (args[1] as UserSnapshot?);
          try {
            api.newUserSnapshot(arg_handle!, arg_snapshot);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.talkjs_core_flutter.CoreFlutterApi.newUserOnlineSnapshot$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.talkjs_core_flutter.CoreFlutterApi.newUserOnlineSnapshot was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_handle = (args[0] as int?);
          assert(
            arg_handle != null,
            'Argument for dev.flutter.pigeon.talkjs_core_flutter.CoreFlutterApi.newUserOnlineSnapshot was null, expected non-null int.',
          );
          final UserOnlineSnapshot? arg_snapshot =
              (args[1] as UserOnlineSnapshot?);
          try {
            api.newUserOnlineSnapshot(arg_handle!, arg_snapshot);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
